name: CI/CD K8S Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7  # 최신 버전 사용

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0  # 최신 버전 사용

      - name: Cache Docker layers
        uses: actions/cache@v4.0.2  # 최신 버전 사용
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push --tag springboothate/argocdtest:${{ github.sha }} .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v4.1.7  # 최신 버전 사용
        with:
          repository: steamedEggMaster/cicdk8s-manifest
          path: manifests
          token: ${{ secrets.FLOW_DEPLOY_KEY }}

      - name: Update manifest
        run: |
          sed -i "s|image: .*|image: springboothate/argocdtest:${{ github.sha }}|" manifests/cicdk8s-main/deployment.yaml

      - name: Commit and push changes
        working-directory: manifests
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update image to springboothate/argocdtest:${{ github.sha }}"
          git push
